export const APP_ROUTES = {
  dashboard: "/",
  files: "/files",
  fileDetail: (fileId: string) => `/files/${fileId}`,
  jobs: "/jobs",
  jobDetail: (jobId: string) => `/jobs/${jobId}`,
  workers: "/workers",
  workerDetail: (workerId: string) => `/workers/${workerId}`,
  review: "/review",
  reviewDetail: (itemId: string) => `/review/${itemId}`,
  reports: "/reports",
  system: "/system",
  config: "/config",
  login: "/login",
} as const;
