"""Shared enums, release helpers, and small utility types for encodr."""

from encodr_shared.path_mappings import (
    MARKER_RELATIVE_PATH,
    ensure_mapping_marker,
    mapping_for_server_path,
    normalise_path_mappings,
    remap_server_path,
    validate_worker_path_mapping,
)
from encodr_shared.backend_preferences import (
    ACCELERATED_HARDWARE_HINTS,
    CPU_HARDWARE_HINT,
    DEFAULT_BACKEND_PREFERENCE,
    DEFAULT_NORMALISED_BACKEND,
    INTEL_BACKEND_PREFERENCES,
    SUPPORTED_BACKEND_PREFERENCES,
    backend_preference_label,
    coerce_backend_preference,
    hardware_hints_from_backend_probes,
    is_supported_backend_preference,
    probe_backend_for_preference,
)
from encodr_shared.runtime_payloads import (
    RUNTIME_SUMMARY_KEYS,
    clean_runtime_summary_payload,
    merge_runtime_summary_preferences,
)
from encodr_shared.setup_state import load_execution_preferences
from encodr_shared.telemetry import collect_runtime_telemetry
from encodr_shared.diagnostics import (
    build_diagnostic_bundle,
    cleanup_old_logs,
    configure_component_logging,
    read_log_events,
    redact_mapping,
    redact_secrets,
)
from encodr_shared.update import UpdateCheckResult, UpdateCheckSettings, UpdateChecker
from encodr_shared.versioning import find_project_root, is_version_newer, parse_version, read_version
from encodr_shared.worker_policy import recommend_worker_concurrency
from encodr_shared.worker_runtime import (
    backend_preference_key,
    backend_preference_keys,
    backend_probe_matches_preference,
    detect_ffmpeg_hwaccels,
    discover_runtime_devices,
    normalise_backend_preference_key,
    probe_binary,
    probe_device_node,
    probe_directory,
    probe_execution_backends,
    probe_intel_qsv,
    probe_intel_vaapi,
    probe_vaapi,
    probe_which,
    resolve_backend_runtime_status,
    serialise_backend_probe,
    serialise_binary_probe,
)

__all__ = [
    "UpdateCheckResult",
    "UpdateCheckSettings",
    "UpdateChecker",
    "ACCELERATED_HARDWARE_HINTS",
    "CPU_HARDWARE_HINT",
    "DEFAULT_BACKEND_PREFERENCE",
    "DEFAULT_NORMALISED_BACKEND",
    "INTEL_BACKEND_PREFERENCES",
    "MARKER_RELATIVE_PATH",
    "RUNTIME_SUMMARY_KEYS",
    "SUPPORTED_BACKEND_PREFERENCES",
    "backend_preference_label",
    "build_diagnostic_bundle",
    "clean_runtime_summary_payload",
    "cleanup_old_logs",
    "collect_runtime_telemetry",
    "configure_component_logging",
    "coerce_backend_preference",
    "load_execution_preferences",
    "backend_preference_key",
    "backend_preference_keys",
    "backend_probe_matches_preference",
    "detect_ffmpeg_hwaccels",
    "discover_runtime_devices",
    "ensure_mapping_marker",
    "find_project_root",
    "hardware_hints_from_backend_probes",
    "is_supported_backend_preference",
    "is_version_newer",
    "mapping_for_server_path",
    "merge_runtime_summary_preferences",
    "normalise_backend_preference_key",
    "normalise_path_mappings",
    "parse_version",
    "probe_binary",
    "probe_backend_for_preference",
    "probe_device_node",
    "probe_directory",
    "probe_execution_backends",
    "probe_intel_qsv",
    "probe_intel_vaapi",
    "probe_vaapi",
    "probe_which",
    "read_version",
    "read_log_events",
    "redact_mapping",
    "redact_secrets",
    "recommend_worker_concurrency",
    "remap_server_path",
    "resolve_backend_runtime_status",
    "serialise_backend_probe",
    "serialise_binary_probe",
    "validate_worker_path_mapping",
]
