from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import subprocess

from encodr_shared.worker_runtime import discover_runtime_devices


RUNTIME_COMPOSE_RELATIVE_PATH = Path(".runtime/compose.runtime.yml")
RUNTIME_PROFILE_RELATIVE_PATH = Path(".runtime/compose.runtime.json")
TARGET_SERVICES = ("api", "worker", "worker-agent")


@dataclass(frozen=True, slots=True)
class RuntimeComposeProfile:
    dri_devices: tuple[str, ...]
    nvidia_devices_present: bool
    nvidia_runtime_available: bool
    warnings: tuple[str, ...]


def build_runtime_compose_profile() -> RuntimeComposeProfile:
    runtime_devices = discover_runtime_devices()
    dri_devices = tuple(
        item["path"]
        for item in runtime_devices
        if item.get("exists") and str(item.get("path", "")).startswith("/dev/dri/")
    )
    nvidia_devices_present = any(
        item.get("exists") and str(item.get("path", "")).startswith("/dev/nvidia")
        for item in runtime_devices
    )
    nvidia_runtime_available = detect_nvidia_runtime()

    warnings: list[str] = []
    if nvidia_devices_present and not nvidia_runtime_available:
        warnings.append(
            "NVIDIA device nodes are present, but the Docker runtime does not report NVIDIA GPU support."
        )

    return RuntimeComposeProfile(
        dri_devices=tuple(sorted(set(dri_devices))),
        nvidia_devices_present=nvidia_devices_present,
        nvidia_runtime_available=nvidia_runtime_available,
        warnings=tuple(warnings),
    )


def detect_nvidia_runtime() -> bool:
    try:
        completed = subprocess.run(
            ["docker", "info", "--format", "{{json .Runtimes}}"],
            check=False,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    if completed.returncode != 0:
        return False
    raw = (completed.stdout or "").strip()
    if not raw:
        return False
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        return False
    return isinstance(payload, dict) and "nvidia" in payload


def render_runtime_compose(profile: RuntimeComposeProfile) -> str:
    lines: list[str] = ["# This file is generated by Encodr. Do not edit it by hand."]
    if not any([profile.dri_devices, profile.nvidia_devices_present and profile.nvidia_runtime_available]):
        lines.append("services: {}")
        return "\n".join(lines) + "\n"

    lines.append("services:")
    for service_name in TARGET_SERVICES:
        lines.append(f"  {service_name}:")
        if profile.dri_devices:
            lines.append("    devices:")
            for device in profile.dri_devices:
                lines.append(f"      - {device}:{device}")
        if profile.dri_devices:
            lines.append("    volumes:")
            lines.append("      - /sys/class/drm:/sys/class/drm:ro")
            lines.append("      - /sys/class/hwmon:/sys/class/hwmon:ro")
        if profile.nvidia_devices_present and profile.nvidia_runtime_available:
            lines.append("    gpus: all")
            lines.append("    environment:")
            lines.append("      NVIDIA_VISIBLE_DEVICES: all")
            lines.append("      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video")
    return "\n".join(lines) + "\n"


def write_runtime_compose_files(project_root: Path | str) -> RuntimeComposeProfile:
    resolved_root = Path(project_root).resolve()
    runtime_compose_path = resolved_root / RUNTIME_COMPOSE_RELATIVE_PATH
    runtime_profile_path = resolved_root / RUNTIME_PROFILE_RELATIVE_PATH
    runtime_compose_path.parent.mkdir(parents=True, exist_ok=True)

    profile = build_runtime_compose_profile()
    runtime_compose_path.write_text(render_runtime_compose(profile), encoding="utf-8")
    runtime_profile_path.write_text(
        json.dumps(
            {
                "dri_devices": list(profile.dri_devices),
                "nvidia_devices_present": profile.nvidia_devices_present,
                "nvidia_runtime_available": profile.nvidia_runtime_available,
                "warnings": list(profile.warnings),
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return profile
